[[redirects]]
  from = "/__/auth/handler"
  to = "https://bandish-editor.firebaseapp.com/__/auth/handler"
  status = 200
  force = true 

[[redirects]]
  from = "/view/*"
  to = "/index.html"
  status = 200
  force = true 

[context.production]
  command = "npm install && npm run release"
  publish = "resources/public"

[context.my]
  command = "lein uberjar"
  publish = "resources/public"

