[[redirects]]
  from = "/__/auth/*"
  to = "https://bandish-editor.firebaseapp.com/__/auth/:splat"
  status = 200

[[redirects]]
  from = "/view/*"
  to = "/index.html"
  status = 200
  force = true 

[[redirects]]
  from = "/sounds/*"
  to = "https://storage.googleapis.com/swaranotebook_media/sounds/:splat"
 
[context.production]
  command = "npm install && npm run release"
  publish = "resources/public"

[context.my]
  command = "lein uberjar"
  publish = "resources/public"

